BUG: Fix ITKExpat conflict by setting ITK COMPONENTS ITKExpat REQUIRED Previous commit 1fac97e99e70ecd2b1ca422f2ef01e2cb12e32e5 removes the library ITKEXPAT originally added in Slicer r317 [1] (ENH: Added examples) from the list of explicit example dependencies. Instead, this commit fixes the error report below by adding ITKEXPAT as a dependency of ModuleDescriptionParser that will be linked into both the examples and any other CLIs. It will prevent linking against incorrect library found on the system.
[1] http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=317

Fixes :
../bin/libModuleDescriptionParser.so: undefined reference to `XML_ParserCreate'
../bin/libModuleDescriptionParser.so: undefined reference to `XML_GetErrorCode'
../bin/libModuleDescriptionParser.so: undefined reference to `XML_SetUserData'
../bin/libModuleDescriptionParser.so: undefined reference to `XML_GetSpecifiedAttributeCount'
../bin/libModuleDescriptionParser.so: undefined reference to `XML_GetCurrentLineNumber'
../bin/libModuleDescriptionParser.so: undefined reference to `XML_ErrorString'
../bin/libModuleDescriptionParser.so: undefined reference to `XML_ParserFree'
../bin/libModuleDescriptionParser.so: undefined reference to `XML_SetElementHandler'
../bin/libModuleDescriptionParser.so: undefined reference to `XML_Parse'
../bin/libModuleDescriptionParser.so: undefined reference to `XML_SetCharacterDataHandler'
collect2: error: ld returned 1 exit status
make[2]: *** [ModuleDescriptionParser/bin/Parser1Test] Error 1
make[1]: *** [ModuleDescriptionParser/Testing/CMakeFiles/Parser1Test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....